/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    "Power Buildings": "电力建筑",
    "Industrial Buildings": "工业建筑",
    "Storage Buildings": "存储建筑",
    "Science Buildings": "科研建筑",
    "Military Buildings": "军事建筑",
    "Public Buildings": "公共建筑",
    "Residental Buildings": "住宅建筑",
    "Orbit Buildings": "行星轨道建筑",
    "Moon Buildings": "月球建筑",
    "Aid Buildings": "冥王星建筑",
    "Venus Buildings": "金星建筑",
    "Outer Orbit Buildings": "外层轨道建筑",
    "XP": "经验点数",
    "Drone Masterity": "无人机精通",
    "Drone Solar Panel": "无人机太阳能电池板",
    "Power Masterity": "电力精通",
    "Mining Masterity": "采矿精通",
    "Nature Masterity": "自然精通",
    "Gas And Liquids": "液体与气体精通",
    "Building Masterity": "建筑精通",
    "Electronics Masterity": "电子精通",
    "Rocket Masterity": "火箭精通",
    "Organics Masterity": "有机物精通",
    "Science Masterity": "科研精通",
    "Power Capacity": "电力上限",
    "Materials Capacity": "固体材料上限",
    "Liquids Capacity": "液体上限",
    "Research Capacity": "研究上限",
    "Aesthetics Consumption": "美学消耗",
    "Health Consumption": "医疗保健消耗",
    "Entertainment Consumption": "娱乐消耗",
    "Religion Consumption": "宗教消耗",
    "Security Consumption": "安保消耗",
    "Start": "开始",
    "Production": "生产",
    "Capacity": "资源上限",
    "Colony": "殖民地",
    "Crust": "地壳",
    "Gravity": "重力",
    "Size": "大小",
    "Humidity": "湿度",
    "Temperature": "温度",
    "Small": "小型",
    "Large": "大型",
    "Ore Rich": "矿物丰富",
    "Platinum Rich": "铂金丰富",
    "Ore Poor": "矿物贫瘠",
    "Platinum Poor": "铂金贫瘠",
    "Wet": "潮湿",
    "Dry": "干燥",
    "Cold": "寒冷",
    "Hot": "炎热",
    "Charge": "充电",
    "Recover your power": "恢复您的电力",
    "Drill Rock": "开采石头",
    "Spend power to drill some rocks for stone": "消耗电力钻岩，以获得一些石头",
    "Drill Ore": "开采矿石",
    "Spend power to mine some ore": "消耗电力开采一些矿石",
    "Collect Biomass": "收集生物质",
    "Dig the soil for organic matter to gather some biomass": "消耗电力挖掘土壤，以获得一些生物质",
    "Power": "电力",
    "Water": "水",
    "Nutrition": "营养物质",
    "Oxygen": "氧气",
    "Wood": "木头",
    "Stone": "石头",
    "Ore": "矿石",
    "Metal": "金属",
    "Platinum": "铂金",
    "Biomass": "生物质",
    "Research": "研究",
    "Beam": "木梁",
    "Brick": "砖块",
    "Plate": "金属板",
    "Fuel": "燃料",
    "Rubber": "橡胶",
    "Plastic": "塑料",
    "Wire": "金属丝",
    "Semiconductor": "半导体",
    "Computer": "电脑",
    "Rocket": "火箭",
    "Graphene": "石墨烯",
    "Magneto": "磁电机",
    "Knowledge Point": "知识点数",
    "XP": "经验点数",
    "Entertainment": "娱乐",
    "Healthcare": "卫生保健",
    "Aesthetics": "美学",
    "Security": "安保",
    "Religion": "宗教",
    "Never": "永不",
    "Repair Drill": "修理钻头",
    "Allows drilling harder materials. Also improves stone output": "允许开采更硬的材料。提高石材产量",
    "Repair Charging Cable": "修理充电线路",
    "Improves power output": "提高电力输出",
    "Repair Manipulators": "修理机械手",
    "Allows digging and picking more materials": "允许挖掘、收集更多类型的材料。提高生物质产量",
    "Auto-quarrying": "自动采石",
    "Allows building quarries that gather stone automatically": "解锁采石场，它将消耗少许电力自动收集石头",
    "Repair Machinery": "修理机器",
    "Repair mining machinery. Improves your automatic quarries and mines by 50%": "修理采矿机器。采石场和矿井产量提高50%",
    "Auto-miners": "自动采矿",
    "Allows building mines that gather ore automatically": "解锁矿井，它将消耗少许电力自动收集矿石",
    "Combustion": "燃烧",
    "Allows producing electrical power by burning biomass": "允许建造能燃烧生物质自动发电的热力发电厂",
    "Repair Storage Module": "修理存储模块",
    "Repair the storage module. Allows building storage sections": "修理飞船上的存储模块。允许建造存储区域",
    "Repair Battery": "修理电池",
    "Improves power storage by +20": "提高电力上限 20",
    "Combustion Chambers": "燃烧室",
    "Extra combustion chambers decrease biomass consumption of thermoelectric power plants by 25%": "为热力发电厂增加额外的燃烧室。使其生物质消耗降低 25%",
    "Improved Quarry": "采石场改良",
    "Modify conveyor belts of your quarries to increases their output by 25%": "改良采石场的传送带。使其产量提升 25%",
    "Improved Mine": "矿井改良",
    "Modify conveyor belts of your mines to increases their output by 25%": "改良矿井的传送带。使其产量提升 25%",
    "Improved Combustion": "燃烧改良",
    "Regulate the flow of raw materials to stabilize the combustion process. Increases thermal plant output by 25%": "控制原料的流速，以使燃烧过程更稳定。使热力发电厂的产量提升 25%",
    "Improved Bio Technology": "生物技术改良",
    "Create a better environment for biological growth. Increases incubators output by 25%": "为微生物生长提供更好的环境。使细菌培养箱的产量提升 25%",
    "Improved Storage": "存储改良",
    "Increases stone, ore and biomass storage from storage sections and hubs by 25%": "存储区域和存储中心的石头、矿石、生物质上限提升 25%",
    "Bacteria Selection": "菌种筛选",
    "Create and cultivate a more complex bio-form. Increases electricity consumption by incubators, but incubators start producing oxygen": "制造、培养一种结构更复杂的微生物。细菌培养箱的电力消耗提升，但能生产氧气",
    "Improved Thermal Plants": "热力发电厂改良",
    "Modify the delivery mechanism to work at higher speeds. Increases thermal plant output by 25%": "优化运输机制，让热力发电厂能以更高的速度运作。热力发电厂的产量提升 25%",
    "Oxidize Combustion Chambers": "氧化燃烧室",
    "Add oxygen to maintain a stronger pressure. Thermal plants are 50% more efficient, but now require oxygen": "向燃烧室中直接注入氧气，大大提升其燃烧效率。热力发电厂的产量提升 50%，但需要消耗氧气",
    "Oxygen Compressors": "氧气压缩机",
    "Allows building oxygen compressors to store more oxygen": "允许建造氧气压缩机以储存更多氧气",
    "Reserve Batteries": "备用电池",
    "Thermoelectric plants now also provide small power storage": "热力发电厂现在也提供少量电力上限",
    "Water Pumping": "抽水技术",
    "Perform a geological survey to find deposits of underground water. Allows building water pumps": "进行详细的地质调查，找到隐藏的地下水。解锁水泵",
    "Electrolytes": "电解质",
    "Allows building extra batteries to store power. Also, improves power output by 20%": "允许建造额外的电池来储存电力。此外，电力产量提升 20%",
    "Repair Supply Module": "修理生命维持模块",
    "Repair the supply module to start generating a trace amount of nutrition": "修理飞船上的生命维持模块，它将产出微量的营养物质",
    "Repair Docking Module": "修理对接模块",
    "Enables colonists arrival": "使殖民者能登上星球表面",
    "Repair Research Module": "修理研究模块",
    "Repair the research module to allow colonists to work as researchers and produce research": "修理研究模块，使殖民者能以研究者的身份工作，并产出研究点",
    "Cargo Sorting": "货物分拣",
    "Repairs sorting machinery. Gives 75% bonus to stone, ore and biomass storage": "修理分拣机。石头、矿石、生物质上限提升 75%",
    "Farming Tools": "农具",
    "Provide some basic tools to your farmers. Improves farming output by 10%": "为您的农民提供一些基本的工具。农民的产量提升 10%",
    "Deep Mining": "深井采矿",
    "Expand your mining shaft network. Improves stone and ore output by 20%": "向地底进一步扩张您的矿井。石头、矿石的产量提升 20%",
    "Underground Vaults": "地下金库",
    "Dig an underground storage for your basic materials, which increases storage facilities by 50%": "在地下挖一个空间来存储基本材料。存储设施的上限提升 50%",
    "Cargo Cranes": "货运起重机",
    "Add cargo cranes to help with sorting. Further improves your storage facilities by 50%": "建造货运起重机，让您可以分类存储货物。存储设施的上限提升 50%",
    "Building Cranes": "建筑起重机",
    "Assemble giant cranes to help constructing new buildings. Decreases price scaling of buildings by 10%": "设置建筑起重机，帮助您建造新的建筑物。建筑升级时的成本提升率降低 10%",
    "Water Deposits": "地下水沉积",
    "Survey deeper layers to find underground water deposits. Improves water production by 20%": "调查更深的地层来寻找沉积的地下水。水产量提升 20%",
    "Flammable Biomass": "易燃生物质",
    "Cultivate a special flammable biomass that produces more heat when burnt, increasing power generation from your thermal plants by 50%": "培育一种特殊的易燃生物质，燃烧时会产生更多的热量。热力发电厂的产量提升 50%",
    "Nutritious Flora": "富营养植物",
    "Plant some special flora in your incubators that increases bacterial growth when decomposing. Makes incubators 50% more productive": "在您的细菌培养箱中放置特殊的植物，这种植物在被分解时可以促进细菌的生长。细菌培养箱的产量提升 50%",
    "Fertilizing": "施肥",
    "Start adding fertilizers to the soil. Your farmers will start using 0.1 biomass each, but it will increase their nutrition output by 30%": "向土壤中添加肥料。每位农民将每秒消耗 0.1 生物质，但其营养物质产量提升 30%",
    "Forester Tools": "林务员工具",
    "Create new tools for your foresters to increases wood output by 25%": "为林务员打造新工具。木材产量提升 25%",
    "Broad-Leaved Forests": "阔叶林",
    "Start planting trees with broad leaves. Forests plants generate oxygen": "开始种植阔叶植物。森林将会产生氧气",
    "Wooden Furniture": "木制家具",
    "Using wooden furniture allows housing an extra colonist in every cabin": "使用木制家具。每个小屋可以容纳一名额外的殖民者",
    "Metal Tools": "金属制工具",
    "Create metal tools to improve wood output of foresters by 50%": "制造金属工具，使林务员的木材产量提升 50%",
    "Metal Machine Parts": "金属制机械零件",
    "Replace old parts with metal, which improves stone and ore output by 50%": "用金属零件替换旧的零件。石头和矿石产量提升 50%",
    "Metal containers": "金属制容器",
    "Use local-sourced metal to improve storage containers. Improves all resources storages by 50%": "使用这颗星球上的金属来改良存储容器。所有资源上限提升 50%",
    "Better cables": "优质电缆",
    "Use more conductive materials in your wiring. Improves power capacity by 75% and output by 25%": "在电线中使用更加导电的材料。电力产量提升25%，电力上限提升 75%",
    "Rangers": "护林员",
    "Teach your foresters better conservation methods. Improves foresters output by 25%": "教会您的林务员如何更好地保护森林。林务员的产量提升 25%",
    "Fruit Trees": "果树",
    "Plant fruit trees in your forests. Forest plants now also provide nutrition": "在您的森林里种植果树。森林将会产出营养物质",
    "Natural Environment": "自然环境",
    "Forest ecosystem is favourable for plant growth. Forest plants now boost biomass production by 2% each": "森林的生态系统有利于植物的生长。每个森林将会使生物质产量提升 2%",
    "Advanced Water Filtering": "高级水过滤",
    "Better filtration methods allow reusing more water. Improves water output by 25%": "优化水过滤方式，使您可以回收利用更多的水。水产量提升 25%",
    "Chemical Analysis": "化学分析",
    "Study chemical reactions. Improves science output by 25%": "研究化学反应。科学产量提升 25%",
    "Improved Electrolytes": "改良电解质",
    "Create new electrolyte solution to improve power capacity by 25%": "创造新的电解质溶液。电力上限提升 25%",
    "Platinum Mining": "铂金开采",
    "Allows colonist miners to extract platinum": "允许矿工开采铂金",
    "Platinum Drills": "铂金钻头",
    "Replace drill heads with platinum. Improves stone and ore output by 40%": "将钻头的材料替换为铂金。石头和矿石产量提升 40%",
    "Platinum Tools": "铂金工具",
    "Create platinum tools to provide additional production boost. Increases wood production and beam, brick and plate crafting by 10%": "制造铂金工具，进一步提高产量。木材、木梁、砖块、金属板的产量提升 10%",
    "Cottages": "小屋",
    "Create plans for a new housing unit": "在您的星球表面建造新的住房单位",
    "Entertainment": "娱乐",
    "Society research allows better understanding of human needs. Unlocks new ways to boost population happiness": "进行社会研究，进一步了解人民的需求。解锁提高人口幸福度的新方法",
    "Social Research Center": "社会研究中心",
    "Unlocks new scientific building for studying sociology": "解锁用于研究社会学的全新科研建筑",
    "Advanced Metallurgy": "高级冶金学",
    "Improved smelting technique increases smelter output by 15%": "改良冶炼技术。使冶炼厂的产量提升 15%",
    "Heat Insulating Chambers": "隔热燃烧室",
    "Create insulation for combustion chambers. Improves thermal plant efficiency by 20%": "为燃烧室增加隔热层。热力发电厂的产量提升 20%",
    "Composite Metals": "复合金属",
    "Using composite metals allows to increase crafting output for plates and wires by 20%": "在工艺制作中使用复合金属。金属板和电线的产量提升 20%",
    "Upgrade Wiring": "优化布线",
    "Lay new wires to further increase power supply by 5%": "铺设新的电线。电力产量提升 5%",
    "Energy Saving": "节能技术",
    "Implement energy saving mode for downtime to significantly save on power. Reduces building power cost by 20%": "停机时使用节能模式，大幅节约用电。建造和升级建筑物时的电力消耗降低 20%",
    "Saving Expedition Drones": "节能探险无人机",
    "Rerout extra energy toward terrain scanners of your expedition drones. Increases expedition loot by 30%": "使用更节能的探险无人机，并将节约的电力分配给其搭载的地形扫描系统。探险战利品提升 30%",
    "Vacuum Sealing": "真空密封",
    "Allows building air-tight containers, increasing storage capacity": "建造密封性更好的存储容器，它可以提升仓库的存储上限",
    "Rubber Padding": "橡胶成型",
    "Add rubber padding to your buildings to further descrease building cost scaling by 10%": "向您的建筑物中加入橡胶。进一步将建筑升级时的成本提升率降低 10%",
    "Surveillance Cameras": "监控摄像头",
    "Install surveillance cameras around your colony. Improves policemen efficiency by 25%": "在您的殖民地附近安装监控摄像头。警察的安保加成提升 25%",
    "Computers": "电脑",
    "Unlocks computers crafting and building data-centers": "解锁电脑制造和数据中心的建造",
    "Industry Automation": "工业自动化",
    "Automate some mundane tasks of your artisans. Gain 5% bonus to all crafting": "将您工匠手上的一些重复性的任务用机器自动化。所有工艺产量提升 5%",
    "3D Printers Construction": "3D 打印建造",
    "Create prefabricated sections on your 3D printers. Further decreases building cost scaling by 10%": "用 3D 打印机制造建筑的预制部分。进一步将建筑升级时的成本提升率降低 10%",
    "Organs Printing": "器官打印",
    "New synthetic organs allow for a better treatment of your colonists. Unlocks a new social law": "运用新的人造器官可以为您的殖民者提供更好的医疗。解锁一个新的法令",
    "Improve Health Diagnostics": "改良健康诊断",
    "Using computers for diagnostics can significantly improve healthcare services. Each level increases healthcare from clinics by 5%": "使用电脑进行诊断，显著改善医疗保健服务。每级使诊所的医疗保健加成提升 5%",
    "Multistore Warehouses": "多层式仓库",
    "Create a scalable solution for your storage. Your warehouses can now store twice as much goods": "为您的存储创建可扩展的解决方案。仓库的存储上限提升 100%",
    "GMO": "转基因生物",
    "Genetic modification of organisms can help boost nutrition production by 5% and biomass production by 10%": "对生物体实施基因改造。营养物质产量提升 5% ，生物质产量提升 10%",
    "Laser Cutting": "激光切割",
    "Using lasers to cut out metal parts significantly simplifies plates and wires production. Increased plate and wire production by 10%": "使用激光切割金属零件，显著简化金属板和线材的生产。金属板和电线产量提升 10%",
    "Better Photo-Elements": "改良光电元件",
    "Improved photo-element technology allows you to boost solar satellites and solar panels output by 20%": "改进光电元件技术。太阳能卫星和太阳能电池板的产量提升 20%",
    "Improved Lithography": "改良光刻机",
    "New methods of lithography improve assembling processes. Boosts computers production by 10%": "新的光刻方法改进了组装工艺。电脑产量提高 10%",
    "Great Radio Transmitter": "大型无线电发射机",
    "Create a signal transmitter with a much stronger output. Allows you to send signals to other civilizations. Unlocks first prestige level": "创建具有更强输出的信号发射器，使您可以向其他文明发送信号。解锁第一种重置级别",
    "Fuel Conservation": "节省燃料",
    "Improved fuel combustion cycle allows to install less rockets to achieve the same thrust. Reduces rocket consumption by 20% for all space structures and ships": "改进的燃烧循环令更少的火箭也能输出相同的推力。所有空间建筑和飞船的火箭消耗降低 20%",
    "Faster Rockets": "高速火箭",
    "Using improved flight path calculation reduces total flight time. Space tourism is now 50% more efficient": "使用改进的飞行路径计算方式，减少飞行时间。太空旅游的娱乐和美学加成提升 50%",
    "Conductive Nano-Particles": "导电纳米粒子",
    "Using new conductive particles improves the capacity of your batteries and accumulators by 20%": "使用新的导电颗粒。电池和蓄电池的电力上限提升 20%",
    "Nanobots": "纳米机器人",
    "Unlocks nanobots factory building on your satellite that provides bonus to all crafting": "在您的卫星上解锁纳米机器人工厂建造，它将为所有工艺生产提供产量加成",
    "Animal Gene Modification": "动物基因改造",
    "Learn how to artificially change animals through gene modification. Unlocks Zoo": "学习利用基因改造的方法，人为地改变动物的特征。解锁动物园",
    "Gravitational Lensing Study": "引力透镜研究",
    "Learn more about the powerful physical effect from massive celestial bodies that causes the curvature of spacetime. Provides more knowledge about the universe and surrounding stars and boosts space telescope effect by 40%": "进一步研究大质量天体导致时空弯曲的物理效应，以获得更多关于宇宙及周围恒星的知识。太空望远镜的研究点上限提升40%",
    "Radiative Dissociation": "辐射解离",
    "Using radiation can improve dissociation process, improving your electrolytes efficiency.  Improves your power storage facilities by 20%.": "使用辐射可以改良电解流程，提高电解质效率。电力上限提升 20%。",
    "Radiative Catalyzation": "辐射催化",
    "Use radiation in chemical reactions to boost your fuel output by 20%": "在化学反应中使用辐射进行催化。燃料产量提升 20%",
    "Plasma Knife": "等离子刀",
    "Use hot ionized gas to cut metal. Improves plates, wires and rockets output by 10%": "使用热电离气体切割金属。金属板、电线和火箭产量提升 10%",
    "Impulse Engine": "脉冲发动机",
    "Replace traditional fuel burning with modern approach, based on ionized plasma stream accelerated by powerful magnetic field. Further reduces rocket consumption by 20% for all space structures and ships": "将传统燃料替换为用强大磁场加速的等离子流。所有空间建筑和飞船的火箭消耗降低 20%",
    "Transistor Photo-Printing": "晶体管光刻技术",
    "Use photolithography to boost your computers production by 20%": "使用光刻技术，将电脑产量提升 20%",
    "UV-Polymerisation": "紫外聚合",
    "Use ionizing radiation for more efficient polymers generation. Improves plastic and rubber output by 10%": "使用电离辐射更有效地生成聚合物。塑料和橡胶产量提升 10%",
    "Bulletproof polymers": "防弹聚合物",
    "Learn how to make plastic and rubber more durable. Decreasing rubber and plastic prices for all your buildings by 50%": "研究如何使塑料和橡胶更耐用。建造和升级建筑物时的橡胶和塑料成本降低 50%",
    "Cold Synthesis": "低温合成",
    "Decreasing fuel consumption by your thermonuclear power-plant by 25%": "热核发电厂的燃料消耗降低 25%",
    "Optimize High-voltage lines": "优化高压线路",
    "Your knowledge now allows you to optimize your power grid, reducing wires prices by 20% per level": "您的知识可以帮助您优化电网。每级使电线的价格降低 20%",
    "Graphene Synthesis": "石墨烯合成",
    "Learn how to obtain graphene from biomass": "了解如何将生物质合成为石墨烯",
    "Graphene Sensors": "石墨烯传感器",
    "Put extra-sensitive sensors to your telescopes to boost their efficiency by 50%": "向您的太空望远镜中加入高度敏感的传感器。使太空望远镜的研究点上限提升 25%",
    "Graphene Membranes": "石墨烯膜",
    "Use graphene membranes inside your batteries to boost power capacity by 10%": "在电池内部使用石墨烯膜。电力上限提升 10%",
    "Graphene Drills": "石墨烯钻头",
    "Replace drill heads with graphene. Improves stone and ore output by 30%": "将钻头的材料替换为石墨烯。石头和矿石产量提升 30%",
    "Platinum Alloys": "铂合金",
    "Use cheaper but durable platinum alloys in your construction. Decreasing platinum prices for all your buildings by 30%": "在建造中使用更便宜但依然耐用的铂合金。建造和升级建筑物时的铂金消耗降低 30%",
    "Composite Building Materials": "复合建筑材料",
    "Replace regular building materials with new composites. Decreasing bricks cost for all your buildings by 30%": "用新型复合材料替换常规建筑材料。建造和升级建筑物时的砖块消耗降低 30%",
    "Composite Cistern Membrane": "复合水箱膜",
    "Use composite materials in your cisterns to make them maintaining higher pressure. Increase water and oxygen capacity by 25%": "在你的水箱中使用复合材料，使其可以承受更大的压力。水和氧气上限提升 25%",
    "Efficient Colliders": "高效对撞机",
    "Use your particle physic knowledge to reduce magnetic field required for particles acceleration. Reduce hadron collider power consumption by 20%": "运用粒子物理学知识，降低加速粒子所需的磁场强度。强子对撞机的电力消耗降低 20%",
    "Neutron Canon": "中子炮",
    "Use neutrons bombarding to eliminate excess water from materials more efficiently. Increase solid non-metal materials output (such as brick, beam, semiconductor) by 10%": "用中子轰击来高效地从材料中移除多余的水。非金属的固体材料（例如木梁、砖块、半导体）产量提升 10%",
    "Controlled Thermonuclear Reactions": "可控热核反应",
    "Increase thermonuclear power plant output by 10%": "热核发电厂的电力产量提升 10%",
    "Advanced Evaporators": "高级蒸发器",
    "Increase water output by 10%": "水产量提升 10%",
    "Magnetic Field Generators": "磁场发生器",
    "Unlocks crafting Magnetos - portable magnetic field generators that can be used to generate magnetic field to protect your colonists from radiation": "解锁磁电机的制造。磁电机是小型的磁场发生器，可以用于保护你的殖民者免受宇宙辐射的伤害。",
    "Neutrino Detectors": "中微子探测器",
    "Construct compact neutrino detectors and use them to investigate universe. Increase Space telescope efficiency by 25%": "建造建造紧凑型中微子探测器并用它们来研究宇宙。太空望远镜的研究点上限提升 25%",
    "Neutrino Coolers": "中微子冷凝器",
    "Using neutrino as efficient mechanism of getting rid of excess heat allows you maintaining higher temperatures in thermonuclear power plants. Each level increase thermonuclear power plants efficiency by 5%": "使用中微子作为消除多余热量的有效手段，让热核发电站可以保持较高的温度。每级使热核发电站的电力产量提升 5%",
    "Quark Canon": "夸克炮",
    "Even better technology to cut metal. Boosts plate, wire and rocket production by 10% each level": "更好的金属切割技术。每级使金属板、电线和火箭产量提升 10%",
    "Fuel Coolers": "燃料冷凝器",
    "Increase fuel output by 10%": "燃料产量提升 10%",
    "Magneto Cooling": "磁电机冷却",
    "Increase magneto crafting efficiency by 10%": "磁电机产量提升 10%",
    "Improved Refrigeration": "改良保鲜技术",
    "Improved refrigeration technology allows you now storing 20% more nutrition and biomass": "更好的保鲜技术。使营养物质和生物质上限提升 20%",
    "Batteries Coolers": "电池冷凝器",
    "Improved batteries cooling allows you increase their capacity by 10%": "改良电池冷却方式。使电力上限提升 10%",
    "Biomass Freezing": "生物质冷却",
    "Use frozen biomass in your investigations. Reduce Biolabs Biomass consumption by 75%": "允许在科研过程中使用冷藏生物质来替代新鲜的。生物实验室的生物质消耗降低 75%",
    "Orbital Bio-research": "轨道生物研究",
    "Biolabs can perform some research in space now (togglable in laws and order)": "生物实验室可以在太空中进行新的研究（在法律与秩序页面开启或关闭）",
    "Orbital Clinic": "轨道诊所",
    "Orbital Supply Module will now also provide healthcare boost": "轨道生命维持模块现在也将提供医疗保健服务",
    "Nano Biobots": "纳米生物机器人",
    "Using biobots can help curing a lot of diseases. Gain +10% to clinic efficiency ": "运用生物机器人可以治愈非常多的疾病。诊所的产量提高 10%",
    "High Energy Plasma Knife": "高能等离子刀",
    "Better control over nuclei decay allows you create more high-energy plasma knifes, further boosting plate and wire production": "更好地控制原子核衰变，您可以制造更多高能等离子刀，进一步提高金属板和电线的产量",
    "Nuclear Synthesis Control": "核合成控制",
    "Good knowledge about thermonuclear reactions allows you better localize your reactions centers, reducing load on the reactor walls. Allows you cheapen thermonuclear reactors by 50%": "对热核反应的深入了解可以让您更好地定位反应中心，减少反应堆壁上的负载。热核发电站的建造和升级城本降低 50%",
    "Upgrade: ": "升级：",
    "Science": "科学",
    "Economy": "经济学",
    "Social": "社交",
    "Quarry": "采石场",
    "Automatically collects stone": "自动收集石头",
    "Mine": "矿井",
    "Automatically collects ore": "自动收集矿石",
    "Bacteria Incubator": "细菌培养箱",
    "Automatically produces biomass": "自动生产生物质",
    "Thermoelectric Power plant": "热力发电厂",
    "Burns biomass to generate power": "燃烧生物质发电",
    "Thermonuclear plant": "热核发电站",
    "Uses nuclear reactions to generate power": "用热核反应生产大量的电力",
    "Storage Section": "存储区域",
    "Provides additional storage space": "提供额外的存储空间",
    "Storage Hub": "存储中心",
    "Provides more storage space, but consumes power": "提供更多存储空间，但需要消耗电力",
    "Oxygen Compressor": "氧气压缩机",
    "Compresses oxygen for easier storage": "压缩氧气以便于储存",
    "Water Pump": "水泵",
    "Pumps water from underground to provide a steady supply": "从地下抽水以提供稳定的供应",
    "Water Storage": "水存储设施",
    "Provides water storage": "提供水资源的存储功能",
    "Battery": "电池",
    "Provides power storage": "提供电力存储",
    "Residential Module": "住宅模块",
    "Provides living space for 2 colonists": "为 2 名殖民者提供生活空间",
    "Meteorology Station": "气象站",
    "Provides 25 research storage and boosts science output by 2% multiplicatively": "提供 25 研究点上限，并使研究点产量提升 2%",
    "Monument": "纪念碑",
    "Provides some aesthetics": "提供一些美学加成",
    "Clinic": "诊所",
    "Provides basic healthcare service": "提供基本的医疗服务",
    "Park Zone": "公园区域",
    "A zone with rich greenery provides a way to relax for your people": "一片绿意盎然的区域，为您的人民提供放松的方式",
    "Bio Laboratory": "生物实验室",
    "Provides even more research storage and boost research output by 5% multiplicatively": "提供更多的研究存储空间，并使研究点产量提升 5%",
    "Forest Plant": "森林",
    "Rich forest area that generates oxygen": "一片美丽的森林，能够产出氧气",
    "Smelter": "冶炼厂",
    "Burns wood to smelt ore into metal": "燃烧木材，将矿石熔炼成金属",
    "Expedition Center": "探险中心",
    "Dedicated center of exploration provides a 5% multiplicative bonus to your expeditions outcome. Requires power and oxygen": "专门的探险中心，使探险战利品提升 5%。需要消耗电力和氧气",
    "Warehouse": "仓库",
    "Provides more raw materials storage": "提供更多的基础材料上限",
    "Cistern": "蓄水池",
    "Provides oxygen and water storage": "提供氧气和水存储",
    "Cottage": "小屋",
    "Provides additional living space for 2 colonists": "提供足以容纳 2 名殖民者的额外生活空间",
    "Cinema": "电影院",
    "Provides additional entertainment for your people": "为您的人民提供额外的娱乐加成",
    "Social Research Center": "社会研究中心",
    "Provides additional research capacity and generation": "提供额外的研究能力和生成",
    "Metallurgy Complex": "冶金综合体",
    "Provides bonus to metal output": "提升金属的产量",
    "Building Materials Factory": "建筑材料工厂",
    "Provides bonus to bricks, beams and plates production": "提升砖块、木梁和金属板的产量",
    "Storage Container": "存储容器",
    "Provides 5% bonus to your materials storage in warehouses": "仓库的上限提升 5%",
    "Solar Panel": "太阳能电池板",
    "Provides power from solar radiation": "将太阳的辐射转化为电力",
    "Shrine": "圣地",
    "Provides some religious service": "提供少量宗教加成",
    "Data Center": "数据中心",
    "Provides additional research capacity and generation": "提供额外的研究能力和生成",
    "Apartment": "公寓",
    "Provides additional living space for 5 colonists": "提供足以容纳 5 名殖民者的额外生活空间",
    "Temple": "寺庙",
    "Great building devoted to the Gods. Significantly boosts your religion service": "献给众神的伟大建筑。提供显著的宗教加成",
    "Pandemic Research Center": "流行病研究中心",
    "Researches viruses and other diseases. Each level decrease colony healthcare requirements by 5%": "研究病毒和其他疾病。每个级别将殖民地医疗保健要求降低 5%",
    "Administrative Service Center": "行政服务中心",
    "Bureaucratic center of your colony. Each level decrease public services requirements of your people by 2%": "你殖民地的官僚中心。每个级别都会将您人民的公共服务需求降低 2%",
    "Electronics Factory": "电子元件工厂",
    "Provides bonus to wires, semiconductors and computers production": "提升电线、半导体和电脑的产量",
    "Satellite Solar Panel": "卫星太阳能电池板",
    "Provides power from solar radiation. More efficient comparing to planet surface analog": "将太阳辐射转化成电力。和它的地面版本相比效率更高",
    "Orbital Tourism Center": "轨道旅游中心",
    "Small space station that provides some entertainment and aesthetics to your people": "为您的人民提供娱乐和美学加成的小型空间站",
    "Space Telescope": "太空望远镜",
    "Provides research capacity bonus": "提供研究能力加成",
    "Ice Melting Station": "融冰站",
    "Melts ice on your cold satellite to obtain water": "融化冰冷卫星上的冰，以获得水",
    "Fuel Factory": "燃料工厂",
    "Move toxic fuel production outside of your planet to avoid ecology restrictions and enlarge your fuel production capabilities": "将有毒的燃料生产转移到你的星球之外，来规避生态限制，并扩大燃料生产能力",
    "Nanobots Factory": "纳米机器人工厂",
    "Each level provides 3% bonus to all your crafting productions": "每级使所有工艺产量提升 3%",
    "Zoo": "动物园",
    "Place where people can enjoy watching animals similar to ones they saw before on Earth": "人们可以在这里欣赏与他们以前在地球上见过的动物相似的动物",
    "Smelting Complex": "冶炼综合体",
    "Uses ore and power to produce big amount of metal. Produces a lot pollution, so placing it on uninhabited place is preferred": "使用矿石和电力生产大量金属。产生大量污染，所以最好是建在无人居住的地方",
    "Platinum Mine": "铂金矿",
    "Provides stable platinum source, but requires a lot power to operate": "提供稳定的铂金产出，但需要消耗大量电力才能运行",
    "Space Warehouse": "太空仓库",
    "What could be better than warehouse? Yes, only warehouse in space! Also affected by storage containers.": "有什么比仓库还要酷的吗？当然是【太】空中的仓【库啦】！该建筑和仓库类似，能享受存储容器的加成。",
    "Pluto Monument": "冥王星纪念碑",
    "This hostile and hot planet, literally made of iron will remind your people of the god of the Underground. Requires a lot resources, but provides significant motivation to religious people": "这个充满敌意和炎热的星球，字面上是由铁制成的，会让你的人民想起地下之神。需要大量资源，但为宗教人士提供了重要的动力",
    "Flora Plant": "植物区系",
    "Hot and wet climate allows you to produce more biomass here. Requires power however to operate": "炎热潮湿的气候使您可以在这里生产更多的生物质。但需要电源才能运行",
    "Tropic Forest Plant": "热带森林植物",
    "Plant large forest plantations to boost your foresters. Each level provides 3% bonus to wood output, but consumes biomass and water": "种植大型人工林来增强您的林务人员的能力。每个级别为木材产量提供 3% 的奖励，但会消耗生物质和水",
    "Organics Processing Factory": "有机物加工厂",
    "Uses suitable climate to decrease cost of organic materials synthesis. Each level increase rubber and plastic output by 5%": "利用适宜的气候来降低有机材料合成的成本。每级增加橡胶和塑料产量5%",
    "Hadron Collider": "强子对撞机",
    "Consumes huge amount of power, but provides significant research capacity": "消耗大量电力，但提供重要的研究能力",
    "Spaceship Station": "宇宙飞船站",
    "Unlocks building ships. Each level reduce rocket consumption for all buildings by 2%": "解锁建造船只。每个级别都会使所有建筑物的火箭消耗减少 2%",
    "Spaceship Factory": "宇宙飞船工厂",
    "Each level increase rocket output by 5%": "每级增加火箭产量5%",
    "Orbital Living Module": "轨道生活舱",
    "Each level provides additional space for 4 colonists": "每层都为 4 名殖民者提供额外的空间",
    "Orbital Supply Module": "轨道供电模块",
    "Provides general service to your colonists": "为您的殖民者提供一般服务",
    "Base battery": "基础电池",
    "Ship hold": "船舱",
    "Ship hold": "船舱",
    "Ship hold": "船舱",
    "Base": "基础",
    "Population": "人口",
    "Base": "基础",
    "Population": "人口",
    "Base": "基础",
    "Base": "基础",
    "Building: ": "建筑：",
    "Quarrymen": "采石工人",
    "Works at the quarry to mine stone": "在采石场工作以开采石头",
    "Miner": "矿工",
    "Works at the mine to gather ore": "在矿山工作以收集矿石",
    "Researcher": "研究员",
    "Works at the lab to generate research": "在实验室工作以进行研究",
    "Farmer": "农民",
    "Tills the soil and plants crops to generate nutrition": "耕种土壤和种植作物以产生营养",
    "Forester": "林务员",
    "Maintains forests, plants and cuts wood": "维护森林、植物和砍伐木材",
    "Artisan": "工匠",
    "Crafts complex goods out of raw materials or other goods": "用原材料或其他物品制作复杂的物品",
    "Policeman": "警察",
    "Patrols the colony and provides security": "巡逻殖民地并提供安全保障",
    "Job: ": "工作：",
    "Population": "人口",
    "Basic": "基础",
    "Exo Farming": "外星农业",
    "Learn how to work with soil on a foreign planet. Allows employing farmers": "了解如何在外星球上处理土壤。允许雇用农民",
    "Meteorology": "气象学",
    "Learn more about the atmosphere and its weather patterns. Unlocks new upgrades and buildings": "了解更多关于大气及其天气模式的信息。解锁新的升级和建筑",
    "Mineralogy": "矿物学",
    "Learn more about minerals available at your new home": "更深入地了解您新家园所拥有的矿物质",
    "Service Industry": "服务业",
    "Unlock new ways of providing services to your growing colony": "解锁为您不断壮大的殖民地提供服务的新方式",
    "High-Gravity Engineering": "高重力工程",
    "Learn about engineering specific to high gravity conditions": "了解特定于高重力条件的工程",
    "Exo Biology": "外星生物学",
    "Learn more about local organisms": "更深入地了解这里的生物",
    "Exo Forestry": "外来林业",
    "Learn how to grow something bigger in this empty terrain": "了解如何在这片空旷的土地上种植更大的东西",
    "Metallurgy": "冶金",
    "Learn how to work with exotic ores. Unlocks crafting and artisan job": "了解如何处理外来矿石。解锁手工艺和工匠工作",
    "Exo Flora": "外来植物群",
    "Advanced flora researches unlocks new tools to boost agriculture": "先进的植物群研究解锁了促进农业发展的新工具",
    "Chemistry": "化学",
    "Study the material interactions of elements in this foreign environment. Unlocks new materials and upgrades": "研究元素在这种外国环境中的物质相互作用。解锁新材料和升级",
    "Geology": "地质学",
    "Further research precious minerals available at your new habitat": "进一步研究新栖息地的珍贵矿物质",
    "Geography": "地理学",
    "Geography knowledge unlocks expeditions": "对地理学的研究可以解锁探险功能",
    "Sociology": "社会学",
    "Unlocks new ways to make your little society happier and more efficient": "解锁让您的小社会更快乐、更高效的新方法",
    "Material Knowledge": "材料知识",
    "Further advances crafting and metal processing": "进一步推进手工艺和金属加工",
    "Law": "法律",
    "Unlocks new aspects of your colony development": "解锁您的殖民地发展的新方面",
    "Electricity Study": "电力研究",
    "Improves knowledge about conductivity of various materials": "增进对各种材料导电性的了解",
    "Organic Chemistry": "有机化学",
    "Learn about new uses for biomass": "了解生物质的新用途",
    "Electronics": "电子产品",
    "Learn how to produce electronics and incorporate it": "了解如何生产电子产品并将其整合",
    "Civil Service": "公共服务",
    "Unlock new civil service jobs and buildings": "解锁新的公共服务职位和建筑",
    "Unlock new powerful tools that will help you boost your colony development": "解锁新的强大工具，帮助您促进殖民地发展",
    "Advanced Physics": "高等物理学",
    "Learn more about surviving and creating in high gravity conditions": "进一步研究如何在高重力条件下生存和制造",
    "Advanced Anatomy": "高级解剖学",
    "Further research human body can make maintaining larger colony much easier": "对人体的进一步研究令人口的进一步扩张成为可能",
    "Rocket Science": "火箭科学",
    "Literally. There is too little space on our planet, isn't it?": "字面上地。我们星球上的空间太小了，不是吗？",
    "Advanced Biology": "高级生物学",
    "Further advance biology knowledge. Create new methods of boosting nutritional value and unlock new research": "进一步提高生物学知识。创造提高营养价值的新方法并开启新的研究",
    "Radiation Study": "辐射研究",
    "Learn more about impact of radiation on living organisms. Unlocks piloted missions": "详细研究辐射对生物体的影响。解锁载人飞行任务",
    "Quantum Physics": "量子物理学",
    "Better understanding of quantum physics can significantly boost the productivity of your civilization": "更好地理解量子物理学，显著提高你的文明的生产力",
    "Gravity Theory": "重力理论",
    "Better understanding of gravitational forces on flying objects will help with rocket launches. Allows you to send missions to other planets": "更好地了解飞行物体的重力将有助于火箭发射。允许您向其他星球发送任务",
    "Nano-Physics": "纳米物理学",
    "Further research into nanotechnology can increase your civilization productivity even more": "对纳米技术的进一步研究可以进一步提高您的文明生产力",
    "Astrophysics": "天体物理学",
    "Allows to further advance your understanding of celestial bodies through new scientific telescopes": "允许通过新的科学望远镜进一步提高您对天体的理解",
    "Relativity Physics": "相对论物理学",
    "Learn more about spacetime continuum. Unlocks new tech and further traveling": "了解有关时空连续体的更多信息。解锁新技术和更远的旅行",
    "Advanced Genetics": "高级遗传学",
    "Push further your genetics knowledge to learn how species can be modified": "进一步推动您的遗传学知识，了解如何改造物种",
    "Photochemistry": "光化学",
    "Learn more about ionizing radiation impact on chemical reactions. Unlocks new upgrades": "详细了解电离辐射对化学反应的影响。解锁新的升级",
    "High Energy Physics": "高能物理",
    "We are so miserable comparing to bright far stars and supernova explosions. Learn how to deal with more energy to expand your capabilities even more. Unlocks further flights and more important researches": "与明亮的遥远恒星和超新星爆炸相比，我们是如此悲惨。了解如何处理更多能量以进一步扩展您的能力。解锁更多航班和更重要的研究",
    "Photo-Lithography": "光刻法",
    "Use your advances in quantum physics and material knowledge to boost production of tiny things. Unlocks new upgrades": "利用您在量子物理学和材料知识方面的进步来促进微小物体的生产。解锁新升级",
    "Thermonuclear synthesis": "热核合成",
    "Learn more about high temperature physics to unlock new source of power": "了解有关高温物理学的更多信息，以解锁新的能源",
    "Advanced Polymers": "先进聚合物",
    "Utilize a highly ionized environment to generate sophisticated, radiation- and temperature-hardened polymers. Unlocking new upgrades": "利用高度电离的环境来生成复杂的、辐射和温度硬化的聚合物。解锁新升级",
    "Advanced Molecular Physics": "高级分子物理学",
    "Learn how to generate more sophisticated compounds to boost your development": "了解如何生成更复杂的化合物来促进您的发展",
    "Super-conductivity": "超导性",
    "Low temperatures causes some materials become incredibly good conductors. Learn more about this phenomena and how you can use it.": "低温导致某些材料成为非常好的导体。了解有关这种现象以及如何使用它的更多信息。",
    "Advanced Composites": "先进复合材料",
    "Learn how to combine metal with plastic to create extremely heat- and hit-hardened materials. Unlocking new upgrades and resources": "了解如何将金属与塑料结合起来，制造出耐热和耐冲击硬化的材料。解锁新的升级和资源",
    "Magneto-Dynamics": "磁动力学",
    "Running extremely strong current unlocks opportunity to generate huge magnetic field. Learn more about how to maintain and use it": "运行极强的电流可以产生产生巨大磁场的机会。了解更多关于如何维护和使用它的信息",
    "Spaceship Construction": "宇宙飞船建造",
    "Allows building spaceships for interstellar flights": "允许建造用于星际飞行的宇宙飞船",
    "Particle Physics": "粒子物理学",
    "Learn more about elementary particles": "了解有关基本粒子的更多信息",
    "Advanced Space Construction": "先进空间建设",
    "Learn more about building in space": "了解有关太空建筑的更多信息",
    "Advanced Thermodynamics": "高级热力学",
    "Advance your knowledge about high temperature environments": "增进您对高温环境的了解",
    "Exoplanet Science": "系外行星科学",
    "Learn more about exoplanets. Unlocks new option to search planets.": "了解有关系外行星的更多信息。解锁搜索行星的新选项。",
    "Low Temperature Physics": "低温物理",
    "Low temperatures can significantly reduce molecule decay rates. Learn how to use it to generate more sophisticated organics": "低温可以显著降低分子衰变率。了解如何使用它来生成更复杂的有机物",
    "Neutrino Physics": "中微子物理学",
    "Neutrinos are particles that interacts with other matter very weakly. Learn how to use it for your civilization development": "中微子是与其他物质相互作用非常弱的粒子。了解如何将其用于您的文明发展",
    "Quark Physics": "夸克物理",
    "Learn more about what matter is made of": "了解更多关于物质是由什么组成的",
    "Cryogenics": "低温学",
    "Use your previous researches in biology, nanophysics and photochemistry to investigate organisms and viruses creation": "利用您之前在生物学、纳米物理学和光化学方面的研究来研究生物体和病毒的产生",
    "Space Biology": "太空生物学",
    "Learn more about specific of your colonists and other organisms living in space.": "详细了解您的殖民者和生活在太空中的其他生物体的具体情况。",
    "Nano-Biology": "纳米生物学",
    "Use your previous researches in biology, nanophysics and photochemistry to investigate organisms and viruses creation": "利用您之前在生物学、纳米物理学和光化学方面的研究来研究生物体和病毒的产生",
    "Advanced Nuclear Research": "先进核研究",
    "Using your knowledge about what protons and neutrons consists of you can learn more about nuclear manipulations": "利用您对质子和中子组成的知识，您可以了解有关核操作的更多信息",
    "Crafting": "制造",
    "Crafting: ": "制造：",
    "Power up": "通电",
    "Drill some stone": "开采一些石头",
    "Repair facilities": "维修设备",
    "Drill ore": "开采矿石",
    "Further facilities repair": "进一步的设备维修",
    "Collect some organics": "收集一些有机物",
    "Autonomous power supply": "自动化电力供应",
    "Storage facilities": "存储设施",
    "Boost power supply": "提升电力供应",
    "Stone production": "石头生产",
    "Ore production": "矿石生产",
    "Power capacity": "电力容量",
    "Organics utilization": "有机物优化",
    "Economy Boost": "经济提升",
    "More Storage": "更多存储空间",
    "Breath In": "吸气",
    "Basic habitability requirements": "基本宜居性要求",
    "Final preparation": "最后的准备",
    "First colonists": "第一批殖民者",
    "Scientific basics": "基础科学",
    "Population": "人口",
    "Healthcare": "卫生保健",
    "Crafting": "制造",
    "Civilized life": "文明生活",
    "Population": "人口",
    "Advanced Science": "高级科学",
    "Knowledge": "知识",
    "Knowledge of Ancestors": "祖先的知识",
    "Advanced Science": "高级科学",
    "Keep Expansion": "保持扩张",
    'If you feel it\'s too difficult to reach this point - you can keep performing "Transmit Knowledge"': "如果你感觉发展到这一步有困难，可以尝试多次进行传输知识重置",
    "Transmit Knowledge": "传输知识",
    "Energy Superpower": "能源大户",
    "Prepare to leave": "准备离开",
    'Keep unlocking new researches until you unlock "Spaceship Building"': "不断完成新的研究，直至解锁宇宙飞船建造",
    "Spaceship Building": "宇宙飞船建造",
    "New Horizons": "新的地平线",
    "When you colonize new planet you get XP for finishing current one. XP provides some multiplicative bonus to your KP gain when transmit knowledge. Your KP and Transmit Knowledge upgrades persist": "当你殖民新的星球时，你会根据当前的星球获得经验点。经验点会在你获得知识点时提供乘算的加成。你的知识点和传输知识升级在殖民星球时会保留",
    "Drone Mastery": "无人机精通",
    "Learn how to use your drone with more efficiency. Every point increases the output from drone actions by 20%": "了解如何更高效地使用无人机。每级增加无人机操作的产量 20%",
    "Drone Solar Panel": "无人机太阳能电池板",
    "Add a solar panel to your starting drone that grants it small power generation": "为您的起始无人机添加一块太阳能电池板，使其产生少量电力",
    "Power Mastery": "电力精通",
    "Your experience with electrical grids helps with power optimization. Every point boosts power production by 4%": "您在电网方面的经验有助于优化发电过程。每级增加电力产量 4%",
    "Mining Mastery": "采矿精通",
    "Striking the earth can be done in a wide variety of ways. Every point boosts stone, ore, iron and platinum production by 4%": "对矿物的进一步开发可以用多种方式完成。每级增加石头、矿石和铂金产量 4%",
    "Nature Mastery": "自然精通",
    "Extensive knowledge of biology and farming helps with spreading greenery on inhospitable worlds. Every point boosts biomass, wood and nutrition production by 4%": "额外的生物学和农业知识有助于在荒凉的世界上种植绿色植物。每级增加生物质、木材和营养物质产量 4%",
    "Gas & Liquid Mastery": "液体和气体精通",
    "Solid materials are important, but so are other states of matter. Every point boosts oxygen and water production 4%": "固态材料固然重要，但其他形态的材料同样如此。每级增加水和氧气产量 4%",
    "Refining Mastery": "精炼精通",
    "Refined materials lie at the core of all complex structures. Every point boosts beam, brick and plate production by 4%": "精制材料是所有复杂结构的核心。每级增加木梁、砖块和金属板产量 4%",
    "Electronics Mastery": "电子精通",
    "Computers kickstarted a second industrial revolution and are very important in automating the industry. Every point boosts electronics (wire, semiconductor, computer, etc) production by 4%": "电脑启动了第二次工业革命，对工业自动化非常重要。每级增加电子产品（例如电线、半导体、计算机）产量 4%",
    "Rocket Mastery": "火箭精通",
    "Each space colony starts with a rocket trip, and you are good at making rockets. Every point boosts fuel and rockets production by 4%": "每个太空殖民地都从一次火箭之旅开始，而你刚好十分擅长制造火箭。每级增加燃料和火箭产量 4%",
    "Organics Mastery": "有机物精通",
    "Be more efficient in your precious biomass usage. Every point boosts biomass based creatable resources production (such as plastic and rubber) by 4%": "更有效地利用珍贵的生物质。每级增加基于生物质的工艺产量 4% （例如塑料和橡胶）",
    "Power Capacity": "电力容量",
    "More industry facilities require more power. Learn how to build better batteries to increase your power storage. Every point boosts power capacity by 4%": "更多的工业设施需要更多的电力。研究如何制造更好的电池，以增加您的电力上限。每级增加电力上限 4%",
    "Materials Capacity": "固体材料上限",
    "You know all about stocking containers to the top. Every point boosts all solid materials capacity by 4%": "您对存储容器了解无比透彻。每级增加固态材料上限 4%",
    "Gas & Liquid Capacity": "气体和液体容量",
    "You know how important full oxygen tank and filled water storage is. Every point boosts oxygen and water capacity by 4%": "您知道充满水箱和氧气罐是多么重要的事情。每级增加水和氧气上限 4%",
    "Research Capacity": "研究上限",
    "Pursuit of knowledge never stops for someone as cursious as you. Every point increases research capacity by 4%": "对于像您这样充满好奇心的人来说，对知识的追求永远不会停止。每级增加研究点上限 4%",
    "Aesthetics Consumption": "美学消耗",
    "Pretty environment is surprisingly effective at boosting productivity. Every point decreases aesthetics requirements by 4": "漂亮的环境对于提高生产力有着惊人的效果。每级使美观度消耗降低 4",
    "Entertainment Consumption": "娱乐消耗",
    "You are not easily bored and know how to distract people from boredom. Every point decreases entertainment requirements by 4": "你不容易感到无聊，并且知道如何分散人们的无聊感。每级使娱乐消耗降低 4",
    "Religion Consumption": "宗教消耗",
    "In every prayer, a strength of the spirit. From strong spirit, a stronger body. Every point decreases religion requirements by 4": "每一次祈祷都令您充满精神的力量。强大的精神，铸就更强大的肉体。每级使宗教消耗降低 4 点",
    "Security Consumption": "安保消耗",
    "Know when to de-escalate, know when to intervene. Every point decreases security requirements by 4": "您了解如何缓和剑拔弩张的气氛。每级使安保消耗降低 4",
    "Healthcare Consumption": "医疗保健消耗",
    "You know how to review a candidate for a future colony, and how to act when things go wrong. Every point decreases healthcare requirements by 4": "你知道如何审查未来殖民地的候选人，以及当出现问题时如何采取行动。每级使医疗保健消耗降低 4",
    "Complete": "完成",
    "Resource: ": "资源：",
    "Upgrade: ": "升级：",
    "Research: ": "研究：",
    "Building: ": "建筑：",
    "Population": "人口",
    "Knowledge Upgrade: ": "知识升级：",
    "Experimental medicine": "实验性医学",
    "Regulates the use of experimental drugs": "规范实验药物的使用",
    "Forbid All": "禁止所有",
    "Clinics are working in a regular way, providing service using only reliable and tested methods": "诊所正常运作，只使用可靠和经过测试的方法提供服务",
    "Allow All": "全部允许",
    "Using experimental medicine reduces healthcare from clinics, but they also provide a boost to max research": "使用实验医学减少了诊所的医疗保健，但它们也促进了最大的研究",
    "Water Filtering Control": "水过滤控制",
    "Changes the water filtration method": "改变水过滤方法",
    "Quick": "快的",
    "Water pumps are working in regular way": "水泵正常工作",
    "Multi-Stage": "多级",
    "Water pumps consume twice as much power, but increase healthcare by 3 each": "水泵消耗两倍的功率，但每个增加 3 个医疗保健",
    "Research Focus": "研究重点",
    "Setting research as priority through providing better equipment to your scientists can boost the development of your colony, but it won't be cheap": "通过为你的科学家提供更好的设备将研究放在首位可以促进你的殖民地的发展，但它不会便宜",
    "No Extra Support": "无额外支持",
    "Science buildings operate normally": "科学楼正常运行",
    "Minor Support": "次要支持",
    "Grant your scientists better tools to work with. Science buildings consume 25% more power, but provide 5% more research capacity": "为您的科学家提供更好的工作工具。科学建筑多消耗 25% 的电力，但提供多 5% 的研究能力",
    "Major Support": "主要支持",
    "Grant your scientists state-of-the-art tools to work on prototypes. Science buildings consume 75% more power, but provide 10% more research capacity": "为您的科学家提供最先进的工具来处理原型。科学建筑多消耗 75% 的电力，但提供多 10% 的研究能力",
    "Forest Use": "森林利用",
    "Your forest plants can be used in different ways to provide various advantages": "您的森林植物可以以不同的方式使用，以提供各种优势",
    "Lungs of the Colony": "殖民地之肺",
    "Forest plants operate normally": "林业植物正常运转",
    "Nature Reserves": "自然保护区",
    "Forest plants produce 50% less oxygen, but provide a small bonus to aesthetics": "森林植物产生的氧气减少 50%，但对美观有一点好处",
    "Picnic zones": "野餐区域",
    "Forest plants produce 50% less oxygen, but provide a small bonus to entertainment": "森林植物产生的氧气减少了 50%，但为娱乐提供了一点好处",
    "Guards Rations": "卫兵口粮",
    "Regulate rations for your policemen to motivate them to work harder": "规范警察的口粮，以激励他们更加努力地工作",
    "Regular": "常规的",
    "Policemen does not consume additional resources": "警察不消耗额外资源",
    "Extra Rations": "额外口粮",
    "Incentivize your police force to work better with extra rations. Policemen consume extra 0.5 nutrition and 0.2 water each, but provide a better service": "激励你的警察部队用额外的口粮更好地工作。警察每人多消耗 0.5 营养和 0.2 水，但提供更好的服务",
    "Artificial Organs": "人造器官",
    "Using 3D printers in creating organs to heal people can significantly boost healthcare, but religious people won't like it": "使用 3D 打印机制造或修复人体器官可以显著提高医疗加成，但宗教人士可能会因此感到不适",
    "Forbid All": "禁止所有",
    "Artificial implants are banned": "禁止人造器官",
    "Allow": "允许",
    "Improves healthcare service, but decrease religious one": "提升医疗保健加成，降低宗教加成",
    "Woodcutting Policy": "伐木政策",
    "Change forest cutting restrictions in order to balance your wood production and environmental effects": "改变森林砍伐限制以平衡木材生产和环境影响",
    "Minor Regulations": "细则",
    "Aggressive Cutting": "皆伐",
    "Encourage production at the cost of pretty landscape. Foresters produce 20% more wood, but each forester reduces aesthetics by 1.5": "以美丽的风景为代价鼓励生产。林务员多生产 20% 的木材，但每个林务员降低 1.5 美感",
    "Forest Preservation": "森林保护",
    "Encourage limited cutting and frequent replanting. Foresters produce 20% less wood, but each forester increases aesthetics by 1": "鼓励有限的砍伐和频繁的重新种植。林务员降低 20% 的木材产量，但每个林务员增加 1 美感",
    "Coal Burning Regulations": "燃煤法规",
    "Allow or forbid wood usage as coal": "允许或禁止将木材用作煤炭",
    "Forbid All": "禁止所有",
    "There is enough smoke as is, the wood is better used elsewhere. Thermal plants dont use wood": "有足够的烟雾，木头最好用在别处。热力发电厂不使用木材",
    "Limited Use": "有限使用",
    "Allow using a minor amount of wood for thermal plants. Thermal plants are 10% more efficient, but consume 0.01 wood each": "允许热力发电厂使用少量木材。热力发电厂的电力产量提升 10%，但每座热力发电厂每秒需消耗 0.01 木材",
    "Unregulated Use": "不受管制的使用",
    "Time to inflict another industrial revoluion. Thermal plants are 25% more efficient, but consume 0.03 wood each": "是时候发动另一场工业革命了。热力发电厂的效率提升 25%，但每台消耗 0.03 木材",
    "Food Chemical Processing": "食品化工加工",
    "Regulate the chemical processing of food": "规范食品的化学加工",
    "Forbid All": "禁止所有",
    "All food is grown organically and served unprocessed": "所有食物都是有机种植的，无需加工即可直接食用",
    "Efficient Processing": "高效加工",
    "Process food to increase shelf life and nutritional value at the cost of its quality. Provides 10% bonus to nutrition production, but decrease healthcare by 10%": "加工食品以牺牲其质量为代价来延长保质期和营养价值。为营养生产提供 10% 的奖励，但减少 10% 的医疗保健",
    "Smelting Method": "冶炼法",
    "Use alternative methods to boost metal smelting": "使用替代方法促进金属冶炼",
    "Traditional": "传统的",
    "Smelters operate as usually": "冶炼厂以正常的方式运作",
    "Electrothermal": "电热",
    "Smelters use 0.3 power each, but produce 30% more metal": "每个冶炼厂消耗 0.3 功率，但多生产 30% 的金属",
    "Orbital Bio-experiments": "轨道生物实验",
    "Allow your Biolabs to run orbital research expeditions.": "允许您的生物实验室进行轨道研究探险。",
    "Forbid": "禁止",
    "Bio-labs operate normally": "生物实验室正常运行",
    "Allow": "允许",
    "Bio-labs start consuming fuel (0.03 each) but provides 10 times more research capacity": "生物实验室开始消耗燃料（每个 0.03），但提供的研究能力增加了 10 倍",
    "Law ": "法令",
    "Knowledge: ": "知识点",
    "Cold": "寒冷",
    "Hot": "炎热",
    "Ore Poor": "矿物贫瘠",
    "Ore Rich": "矿物丰富",
    "Small": "小型",
    "Big": "大型",
    "Wet": "潮湿",
    "Dry": "干燥",
    "Default": "默认",
    "None": "无",
    "AD": "AD",
    "TOI": "TOI",
    "HAP": "HAP",
    "HAT": "HAT",
    "Gliese": "Gliese",
    "CORROT": "CORROT",
    "Kepler": "Kepler",
    "WASP": "WASP",
    "B": "B",
    "C": "C",
    "D": "D",
    "Planet modifier: ": "行星加成",
    "Stable": "稳定",
    "Small Season Changes": "小幅度季节变化",
    "Moderate Season Changes": "中度季节变化",
    "Big Season Changes": "较大的季节变化",
    "Terrible": "严酷",
    "Very Hot": "酷热",
    "Hot": "炎热",
    "Warm": "温暖",
    "Slightly Warm": "微暖",
    "Normal": "正常",
    "Slightly Cold": "微冷",
    "Cold": "寒冷",
    "Very Cold": "很冷",
    "Extremely Cold": "极冷",
    "Spring": "春天",
    "Summer": "夏天",
    "Autumn": "秋天",
    "Winter": "冬天",
    "Temperature modifier: ": "温度加成：",
    "Expand": "展开",
    "Collapse": "折叠",
    "Goal: ": "目标：",
    "Year ": "年：",
    "Season: ": "季节：",
    "Weather: ": "天气：",
    "Planet": "行星",
    "Science": "科学",
    "Space": "太空",
    "Laws & Order": "法律与秩序",
    "Prestige": "重置",
    "Settings": "设置",
    "About & Change Log": "关于 & 更新日志",
    "Statistics": "统计",
    "Support project": "支持本游戏",
    "Ignited Space": "激燃太空",
    "GMO": "转基因生物",
    "X": "X",
    "Hold Shift to decrease by 5": "按住 Shift 键减少 5",
    "Hold Ctrl to decrease to 0": "按住 Ctrl 键减少到 0",
    "Hold Shift to increase by 5": "按住 Shift 键增加 5",
    "Hold Ctrl to increase to ": "按住 Ctrl 键增加到 ",
    "Never": "从不",
    "K": "K",
    "M": "M",
    "B": "B",
    "T": "T",
    "Drone Actions": "无人机操作",
    "Consume": "消耗",
    "Produce": "生产",
    "Drone Upgrades": "升级",
    "Cost": "成本",
    "Consume": "消耗",
    "Produce": "生产",
    "Storage": "存储",
    "Income Bonuses": "产量加成",
    "Storage Bonuses": "上限加成",
    "Efficiency: ": "效率：",
    "Missing ": "缺少",
    "Cost": "成本",
    "Consume": "消耗",
    "Produce": "生产",
    "Income Bonuses": "产量加成",
    "Storage": "存储",
    "Negative Effect": "负面影响",
    "Positive Effect": "正面作用",
    "To empty: ": "距离耗尽：",
    "To max: ": "距离满仓：",
    "Expedition": "探险",
    "Loot multiplier: x": "战利品乘数：x",
    "Expeditions completed: ": "探险完成次数：",
    "Time to complete: ": "距离完成：",
    "Last Loot": "上次战利品",
    "Colonists": "殖民者",
    "Craftable": "可制作",
    "Consume": "消耗",
    "Produce": "生产",
    "Storage Bonuses": "存储加成",
    "Hold Ctrl to set 0": "按住Ctrl键设置0",
    "Hold Ctrl to set max": "按住 Ctrl 设置最大值",
    "Overview": "概览",
    "Population: ": "人口：",
    "Free colonists: ": "空闲人口：",
    "Happiness: ": "幸福度：",
    "Happiness affects your colonists productivity. Has no effect on machinery production.": "幸福会影响您的殖民者的生产力。对机械生产无影响。",
    "Jobs": "工作",
    "Consume": "消耗",
    "Produce": "生产",
    "Hold Ctrl to set 0": "按住Ctrl键设置0",
    "Hold Ctrl to set max": "按住 Ctrl 设置最大值",
    "Overview": "概览",
    "Crafting Slots: ": "工作中：",
    "Free slots: ": "空闲：",
    "Jobs": "工作",
    "None": "无",
    "Landing zone": "着陆区",
    "Colony": "殖民地",
    "Crafting": "制造",
    "Researches": "研究",
    "Hide researched": "隐藏研究",
    "Show researched": "显示已研究",
    "Consume": "消耗",
    "None": "无",
    "Research": "研究",
    "Game Data": "游戏数据",
    "Export to file": "导出到文件",
    "Export": "导出字符串",
    "Import from file": "从文件导入",
    "UTF-8": "UTF-8",
    "Error importing file": "导入文件错误",
    "Select file": "选择文件",
    "Get export text": "获取导出文本",
    "Export text": "导出文本",
    "Import from text": "从文本导入",
    "Import": "导入字符串",
    "Save": "保存",
    "Hard reset": "硬重置",
    "This action will remove all your game data. Are you sure?": "这个操作会删除您所有的游戏数据，且不可挽回。确定要这么做吗？",
    "Wipe game data": "擦除游戏数据",
    "Science": "科学",
    "Economy": "经济学",
    "Social": "社交",
    "Consume": "消耗",
    "Produce": "生产",
    "Income Bonuses": "产量加成",
    "Storage": "存储",
    "Negative Effect": "负面影响",
    "Positive Effect": "正面作用",
    "This game was pretty much inspired by": "这款游戏受到了",
    "Kittens game": "猫国建设者（Kittens game）",
    ", but it's not a clone.": "的很多启发，但并非一款一模一样的游戏。",
    "You start with broken ship on hostile planet. Your main goal is to prepare for first colonists to arrive, and build prosperous civilisation": "你从敌对星球上的破损船只开始。你的主要目标是为第一批殖民者的到来做好准备，并建立繁荣的文明",
    "By Strange Matter Gaming": "作者：Strange Matter Gaming",
    "Support on Patreon": "在 Patreon 上支持作者",
    "Join our Discord": "加入我们的 Discord 频道",
    "Fixed issue when materials with 0 capacity could be produced": "修复可以生产上限为 0 的材料的问题",
    "Fixed issue when false warning on building efficiency dropped appeared": "修复了建筑效率下降时出现错误警告的问题",
    "Fixed layout issue on smaller screens": "修复了较小屏幕上的布局问题",
    "Added warning on buildings running on lower efficiency": "添加了对低效率运行的建筑物的警告",
    "Updated formula to calculate XP bonus": "更新了计算 XP 奖励的公式",
    "Added new late game content": "添加了新的游戏后期内容",
    "Fixed/changed some goals": "修正/改变了一些目标",
    "Changed game loading mechanism to prevent data loss": "更改游戏加载机制以防止数据丢失",
    "Implemented statistics page": "实现统计页面",
    "Fixed some buildings prices": "修复了一些建筑物的价格",
    "Updated second prestige layer - fixed some formulas": "更新了第二个声望层 - 修复了一些公式",
    "Weather": "天气",
    "Expeditions": "探险",
    "Small UI and QoL fixes": "一些小的 UI 和 QoL 修复",
    "Continued goals": "持续目标",
    "Fixed some bugs in buildings bonuses": "修复了建筑物奖励中的一些错误",
    "Fixed some bugs in prestige mechanics": "修复了声望机制中的一些错误",
    "Increased some buildings efficiency": "提高了一些建筑物的效率",
    "You can now press Shift or Ctrl to batch enable/disable buildings": "您现在可以按 Shift 或 Ctrl 批量启用/禁用建筑物",
    "Fixed UI bug on mobile on pages with small amount of content": "修复了移动设备上内容较少的页面上的 UI 错误",
    "Fixed some other small bugs": "修复了其他一些小错误",
    "Fixed descriptions for some prestige upgrades": "修复了一些声望升级的描述",
    "Fixed bug when Organics mastery was missing": "修复了有机物精通缺失时的错误",
    "Fixed layout issues on some devices": "修复了某些设备上的布局问题",
    "Fixed bug in formula for second layer prestige bonus calculation": "修复了第二层声望奖励计算公式中的错误",
    "Added new late game content": "添加了新的游戏后期内容",
    "Added second prestige level": "增加了第二个声望等级",
    "Increased factories bonuses": "增加工厂奖励",
    "Decreased some upgrades bonuses": "减少了一些升级奖励",
    "Fixed weird scroll behaviour on mobile": "修复了移动设备上奇怪的滚动行为",
    "Fixed some prestige upgrades descriptions": "修复了一些声望升级描述",
    "Fixed display on album-oriented screens": "修复了在面向专辑的屏幕上的显示",
    "Fix bug with building efficiency calculation": "修复建筑效率计算的错误",
    "Add few new researches and buildings": "增加了一些新的研究和建筑物",
    "Added highlight for buildings that use howered resource": "鼠标移动到资源上时，需要使用它的项目将会高亮",
    "Expedition button now on the top": "探险按钮现在位于顶部",
    "Added +/-5 controls for jobs and crafters": "为工作和工匠添加了 +/-5 控制按钮",
    "Colonists now assigned automatically to artisans once you run out of free crafters but have free colonists": "一旦您用完免费工匠但有免费殖民者，殖民者现在会自动分配给工匠",
    "Warehouses now provide nutrition capacity": "仓库现在提供营养能力",
    "Fixed descriptions": "修复描述",
    "Items that require more capacity are now highlighted differently": "需要更多资源上限的项目现在以不同的方式突出显示",
    "Added mobile support (Experimental and might be buggy)": "添加了移动端支持（实验性，可能存在问题）",
    "Fixed bugs with expeditions": "修复了探险的错误",
    "Added notifications for new buildings/upgrades/laws": "增加了新建筑/升级/法令的通知",
    "Re-balanced some buildings: Smelters and Monuments prices reduces, increased Smelter ore upkeep, removed Warehouse power upkeep": "重新平衡一些建筑物：冶炼厂和纪念碑价格降低，提升冶炼厂矿石消耗，删除仓库电力消耗",
    "Added new laws": "增加了新的法令",
    "Added expedition length settings": "增加了探险时长设置",
    "Added 2 new science researches, 3 upgrades and 1 building": "增加了 2 个新的科学研究、3 个升级和 1 个建筑",
    "Fixed some mistakes in descriptions": "修正了描述中的一些错误",
    "Edited upgrade descriptions": "优化部分升级的说明",
    "Fixed bug when not active expedition centers provided boost to expedition multiplier": "修复了未开启的探险中心依然提供探险乘数提升的错误",
    "Fixed bug when locked resources still were displaying in bonuses or requirements list": "修复了未解锁的资源仍然显示在奖励或需求列表中的错误",
    "Expedition center now also requires Geography research": "探险中心需要前置地理学研究",
    "Fixed descriptions of some upgrades": "修复了一些升级的描述",
    "Expeditions": "探险",
    "Inverted colors for in-progress items": "正在进行中的项目会反色显示",
    "Available actions are now highlighted on hover": "可用的操作现在在悬停时突出显示",
    "Items that will never be available now highlighted in different color": "以目前状态无论等待多久都不可用的项目现在以不同颜色突出显示",
    "Controls are shown disabled now when they not available": "控件在不可用时显示为已禁用",
    "Added prestige mechanics": "增加重置机制",
    "Added new early space content (researches, buildings)": "增加新的早期太空内容（研究、建筑）",
    "Negative and capped resources are now highlighted": "净产量为负的资源和达到上限的资源现在突出显示",
    "Fixed bug when max colonists amount could be not integer value": "修复了最大殖民者数量可能不是整数的错误",
    "Added highlight on missing resource when hower over building/upgrade/research": "在建造/升级/研究处添加了对所缺少资源的突出显示",
    "Popups will now appear always to right": "弹出窗口将会出现在画面右侧",
    "Changed size and background for buildable/upgradeable items to make them easier to see/click": "更改了可建造/可升级物品的大小和背景，使其更易于查看/点击",
    "Added manual save and hard reset buttons": "增加手动保存和硬重置按钮",
    "Approximately 48 hours of playable content": "大约 48 小时的可游玩内容",
    "Basic game mechanics: buildings, researches, upgrades, colony management": "基本游戏机制：建筑、研究、升级、殖民地管理",
    "Efficiency: ": "效率：",
    "Missing ": "缺少",
    "Cost": "成本",
    "Consume": "消耗",
    "Produce": "生产",
    "Income Bonuses": "产量加成",
    "Storage": "存储",
    "Negative Effect": "负面影响",
    "Positive Effect": "正面作用",
    "None": "无",
    "Space Constructions": "空间构造",
    "Transmit Knowledge Upgrades: ": "传输知识升级：",
    "Cost": "成本",
    "Transmit knowledge": "传输知识",
    "You will lose all your resources, upgrades, buildings and science. But you will transmit your knowledge to next colonizers, making their progress much faster.": "您将失去所有的资源、升级、建筑和科学。但你会将你的知识传递给下一个殖民者，使他们的进步更快。",
    "You will earn ": "您将获得",
    "knowledge points (based on your current population) that can be used to purchase various upgrades": "知识点，可用于购买各种升级（获取量根据您当前的人口计算）",
    "Are you sure?": "您确定吗",
    "Transmit Knowledge and leave the planet": "传播知识并离开这颗星球",
    "Great Radio Transmitter": "大型无线电发射机",
    "Colonize Planets": "殖民星球",
    "You have ": "你拥有",
    "You will lose all your resources, upgrades, buildings and science. Knowledge points and upgrades you already have will persist. You won't receive any transmit knowledge but you will receive ": "您将失去所有的资源、升级、建筑和科学。知识点和已购买的传输知识升级会保留。你不会获得任何新的知识点，但你会获得",
    "XP points. Your KP gain multiplier will be x": "经验点数。你的知识点获取乘数将会是 x",
    "Are you sure?": "你确定吗？",
    "Days per year: ": "每年天数：",
    "Seasons: ": "季节：",
    "Cost": "成本",
    "Consume": "消耗",
    "Produce": "生产",
    "Storage": "存储",
    "Income Multipliers": "产量倍率：",
    "Storage Multipliers": "上限倍率：",
    "XP Gain: x": "经验点数倍率：x",
    "Weather: x": "天气倍率：x",
    "Select search for specific modifier. This will increase search cost": "搜索特定的行星词缀。这会提高搜索行星时的燃料消耗",
    "None": "无",
    "None": "无",
    "Search New Planets": "搜索新的行星",
    "Regenerate list of planets available for colonization": "重新生成可供殖民的行星列表",
    "Cost": "成本",
    "Colonize": "殖民",
    "You should build Spaceship Orbital Station to be able to reach other stars": "你需要建造宇宙飞船站，才能搜索其他的行星",
    "You have ": "你拥有",
    "Current Planet": "当前行星",
    "Name:": "名称：",
    "Description: ": "描述：",
    "Days per year: ": "每年天数：",
    "Seasons:": "季节：",
    "KP Gain multiplier: ": "知识点获取乘数：",
    "Consume": "消耗",
    "Produce": "生产",
    "Storage": "存储",
    "Income Multipliers": "产量倍率：",
    "Storage Multipliers": "上限倍率：",
    "None": "无",
    "Transmit Knowledge": "传输知识",
    "Colonize New Planet": "殖民新星球",
    "General Statistics": "一般统计",
    "Time In Game": "游戏时间",
    "Transmit Knowledge Prestiges": "传播知识声望",
    "Time This Prestige": "时间这个声望",
    "Total KP Gain (All time)": "KP 总增益（所有时间）",
    "Max KP Gain (per prestige)": "最大 KP 增益（每声望）",
    "Colonize Prestiges": "殖民声望",
    "Time This Planet": "这个星球的时间",
    "Total XP Gain (All time)": "总 XP 增益（所有时间）",
    "Max XP Gain (per prestige)": "最大 XP 增益（每声望）",
    "Maximum Colonists": "最大殖民者",
    "Maximum Happiness": "最大的幸福",
    "General": "一般的",
    "Empty and cold here": "这里空旷寒冷",
    "As a general rule of thumb, a person can survive without water for about 3 days. So, keep your water supply stable otherwise your colony will die": "根据一般经验，一个人可以在没有水的情况下生存大约 3 天。所以，保持供水稳定，否则你的殖民者们就会死亡。",
    "You have to setup basic food and water supply before you can meet first colonists": "在见到第一批殖民者之前，你必须准备好基本的食物和水供应。",
    "The International Space Station completes one full orbit around the Earth every 90 minutes. As a result, its crew observes the sunrise every 90 minutes. Each day, the people on board the ISS witness 16 sunrises and 16 sunsets.": "国际空间站每 90 分钟绕地球一周。因此，其船员每 90 分钟就会观察一次日出。每天，国际空间站上的人们都会见证 16 次日出和 16 次日落。",
    "The magnetic poles of the Earth are in motion. For example, over the past hundred years, the magnetic pole in the Southern Hemisphere has shifted by nearly 900 kilometers and is currently located in the Southern Ocean.": "地球的磁极在运动。例如，近百年来，南半球的磁极移动了近900公里，目前位于南大洋。",
    "The length of blood vessels in our body is approximately 100,000 kilometers.": "我们体内血管的长度约为10万公里。",
    "Neutron stars are known for their incredibly high density. The density of a neutron star is typically around 10^17 to 10^18 kilograms per cubic meter. To put this into perspective, it is estimated that a teaspoonful of neutron star material would weigh about as much as a mountain on Earth.": "中子星以其令人难以置信的高密度而闻名。中子星的密度通常约为每立方米 10^17 至 10^18 千克。从这个角度来看，据估计一茶匙中子星材料的重量相当于地球上一座山的重量。",
    "The first confirmed discovery of an exoplanet (a planet outside our solar system) was announced in 1992. The exoplanet, named PSR B1257+12 b, was found orbiting a pulsar, a rapidly rotating neutron star. Since then, thousands of exoplanets have been discovered using various methods, including radial velocity measurements, transit observations, and direct imaging.": "1992 年，人们首次确认发现了一颗系外行星（太阳系外的行星）。这颗系外行星被命名为 PSR B1257+12 b，被发现绕着一颗快速旋转的中子星脉冲星运行。从那时起，人们利用各种方法发现了数千颗系外行星，包括径向速度测量、凌日观测和直接成像。",
    "One fascinating fact about the universe is that it is constantly expanding. The observations made by astronomers and physicists over the past century have shown that galaxies are moving away from each other in all directions. This discovery led to the development of the Big Bang theory, which suggests that the universe originated from a hot and dense state around 13.8 billion years ago.": "关于宇宙的一个有趣的事实是它在不断膨胀。天文学家和物理学家在过去一个世纪的观察表明，星系正在向各个方向相互远离。这一发现导致了大爆炸理论的发展，该理论表明宇宙起源于大约 138 亿年前的炎热而致密的状态。",
    "Black holes are incredibly dense regions of spacetime with gravity so strong that nothing, not even light, can escape their gravitational pull. They form when massive stars collapse under their own gravity at the end of their life cycles.": "黑洞是极其密集的时空区域，其引力如此之强，以至于任何东西，甚至光，都无法逃脱它们的引力。当大质量恒星在其生命周期结束时在自身引力作用下崩溃时，它们就形成了。",
    "Universe is composed mostly of dark matter and dark energy, which together make up about 95% of the total energy content of the cosmos.": "宇宙主要由暗物质和暗能量组成，它们合计约占宇宙总能量的95%。",
    "Dark matter is a hypothetical form of matter that does not interact with light or other forms of electromagnetic radiation, making it invisible to our telescopes. Its presence is inferred from its gravitational effects on visible matter and the large-scale structure of the universe.": "暗物质是一种假设的物质形式，它不与光或其他形式的电磁辐射相互作用，因此我们的望远镜看不到它。它的存在是从它对可见物质和宇宙大尺度结构的引力效应推断出来的。",
    "The Milky Way is estimated to be home to over 100 billion stars. This vast number of stars makes the Milky Way a typical spiral galaxy, with a relatively average size compared to other galaxies in the universe.": "据估计，银河系拥有超过 1000 亿颗恒星。如此大量的恒星使银河系成为一个典型的螺旋星系，与宇宙中的其他星系相比，其尺寸相对平均。",
    "The closest star to the Sun is Proxima Centauri. It is a small, low-mass star located in the constellation of Centaurus, approximately 4.24 light-years away from us.": "距离太阳最近的恒星是比邻星。它是一颗位于半人马座的小型低质量恒星，距我们约 4.24 光年。",
    "The Ignited Space": "激燃太空",
    "Earth is the densest planet in our solar system. With an average density of approximately 5.5 grams per cubic centimeter, Earth is denser than any other planet in our neighborhood.": "地球是太阳系中密度最大的行星。地球的平均密度约为每立方厘米 5.5 克，比我们附近的任何其他行星都密度大。",
    "Earth is the only planet known to have plate tectonics. Plate tectonics refers to the movement and interaction of large rigid plates that make up the Earth's surface.": "地球是唯一已知具有板块构造的行星。板块构造是指构成地球表面的大型刚性板块的运动和相互作用。",
    "Earth's rotation is gradually slowing down due to the tidal forces exerted by the Moon.": "由于月球施加的潮汐力，地球的自转逐渐减慢。",
    "Earth is the only planet known to have a functioning ozone layer that protects us from ionizing UV-radiation": "地球是已知唯一拥有有效臭氧层的行星，可以保护我们免受电离紫外线辐射。",
    "Venus has the longest rotation period of any planet in our solar system, taking longer to rotate on its axis than it does to orbit the Sun.": "金星是太阳系中自转周期最长的行星，绕其轴自转的时间比绕太阳公转的时间更长。",
    "Venus has a thick and dense atmosphere composed mainly of carbon dioxide, with traces of other gases such as nitrogen and sulfur dioxide.": "金星拥有厚重的大气层，主要由二氧化碳组成，还含有微量的其他气体，如氮气和二氧化硫。",
    'Venus has the longest known volcanic mountain range in our solar system, located on the surface of Venus is a massive volcanic mountain range called the "Maxwell Montes." It stretches for about 1,300 kilometers (800 miles) across Venus\'s highland region known as Ishtar Terra.': "金星拥有太阳系中已知最长的火山山脉，位于金星表面的是一座巨大的火山山脉，称为“麦克斯韦山脉”。 它绵延约 1,300 公里（800 英里），横跨金星的高地地区，即伊什塔尔泰拉 (Ishtar Terra)。",
    "The Moon is tidally locked with Earth, which means that it always shows the same face towards us.": "月球与地球潮汐锁定，这意味着它总是用同一面面对我们。",
    "With a diameter of approximately 3,474 kilometers (2,159 miles), the Moon is the fifth-largest natural satellite orbiting a planet in our solar system. It is surpassed in size by Ganymede (a moon of Jupiter), Titan (a moon of Saturn), Callisto (another moon of Jupiter), and Io (yet another moon of Jupiter).": "月球的直径约为 3,474 公里（2,159 英里），是太阳系中绕行星运行的第五大天然卫星。它的大小被木卫三（木星的卫星）、泰坦（土星的卫星）、木卫四（木星的另一颗卫星）和木卫一（木星的另一颗卫星）超越。",
    "Mars has the largest volcano in the solar system, called Olympus Mons. It measures approximately 22 kilometers (13.6 miles) in height and has a diameter of about 550 kilometers (342 miles).": "火星拥有太阳系中最大的火山，称为奥林匹斯山。它高约 22 公里（13.6 英里），直径约 550 公里（342 英里）。",
    "Mars experiences powerful and massive dust storms that can engulf the entire planet. These storms can last for weeks or even months and cover vast regions, obscuring the Martian surface from view.": "火星上有强大而巨大的沙尘暴，可以吞没整个星球。这些风暴可能会持续数周甚至数月，并覆盖广大地区，使火星表面变得模糊不清。",
    "Mars has the largest canyon in the solar system, known as Valles Marineris, that stretches approximately 4,000 kilometers (2,500 miles) in length, making it the largest known canyon in the solar system. To put it into perspective, Valles Marineris is more than 10 times longer and five times deeper than the Grand Canyon in the United States.": "火星拥有太阳系中最大的峡谷，称为水手谷，长约 4,000 公里（2,500 英里），是太阳系中已知最大的峡谷。客观来看，水手谷比美国大峡谷长10倍以上，深5倍以上。",
    "The Sun is so large that it accounts for more than 99% of the mass in our entire solar system.": "太阳非常大，占整个太阳系质量的 99% 以上。",
    "The Sun is not a solid object, but rather a giant, churning ball of hot plasma.": "太阳不是一个固体，而是一个巨大的、翻腾的热等离子体球。",
    "Light travels at a speed of approximately 299,792 kilometers per second (186,282 miles per second) in a vacuum. Despite this incredible speed, it still takes over 8 minutes for light from the Sun to reach us on Earth due to the vast distance between the two.": "光在真空中的传播速度约为每秒 299,792 公里（每秒 186,282 英里）。尽管速度如此惊人，但由于太阳与地球之间的距离遥远，太阳光仍然需要 8 分钟以上才能到达地球上的我们。",
    "The Sun's magnetic field is a complex and dynamic system that undergoes a complete reversal of its polarity approximately every 11 years. This phenomenon is known as the solar magnetic field reversal or solar magnetic cycle.": "太阳磁场是一个复杂且动态的系统，大约每 11 年就会发生一次极性完全反转。这种现象被称为太阳磁场反转或太阳磁循环。",
    51 Pegasi b, also called "Dimidium," was discovered in 1995 and is located approximately 50 light-years away from Earth in the constellation Pegasus. It was the first exoplanet discovered orbiting a main-sequence star similar to our Sun.': "51 Pegasi b，也称为“Dimidium”，于 1995 年被发现，位于距离地球约 50 光年的飞马座。 这是发现的第一颗围绕类似于太阳的主序恒星运行的系外行星。",
    "The first exoplanet discovered in the habitable zone of its star is called Gliese 581d. It was discovered in 2007 and is located approximately 20.3 light-years away from Earth in the constellation Libra. It orbits the red dwarf star Gliese 581, which is smaller and cooler than our Sun.": "在其恒星的宜居带中发现的第一颗系外行星被称为 Gliese 581d。它于 2007 年被发现，位于距离地球约 20.3 光年的天秤座。它围绕红矮星 Gliese 581 运行，它比太阳更小、温度更低。",
    "When we think of radiation, we often associate it with electromagnetic waves like X-rays, gamma rays, or visible light. However, radiation can also refer to particles emitted during certain radioactive processes.": "当我们想到辐射时，我们经常将其与 X 射线、伽马射线或可见光等电磁波联系起来。然而，辐射也可以指在某些放射性过程中发射的粒子。",
    "During the Big Bang, high-energy radiation was generated as the universe rapidly expanded and cooled. This radiation, known as the cosmic microwave background (CMB), can still be detected today and is considered one of the strongest pieces of evidence supporting the Big Bang theory.": "大爆炸期间，随着宇宙迅速膨胀和冷却，产生高能辐射。这种辐射被称为宇宙微波背景辐射（CMB），至今仍然可以被检测到，并被认为是支持大爆炸理论的最有力的证据之一。",
    'The Earth\'s climate has undergone natural fluctuations throughout its history, including periods of extreme cold called "Snowball Earth" episodes, when whole planet was covered by ice.': "地球的气候在其整个历史中经历了自然波动，包括被称为“雪球地球”时期的极端寒冷时期，当时整个地球都被冰覆盖。",
    "The human body is composed of trillions of cells, but only about 10% of those cells are actually human. Other 90% belongs to viruses, fungi, and other microscopic organisms, collectively known as the human microbiota.": "人体由数万亿个细胞组成，但其中只有约 10% 真正是人类的。其余90%属于病毒、真菌和其他微生物，统称为人类微生物群。",
    "The human brain is one of the most energy-demanding organs in the body, consuming about 20% of the body's total energy.": "人脑是人体最需要能量的器官之一，消耗的能量约占人体总能量的20%。",
    "Loading...": "加载中……",
    "Did you knew?": "你知道吗？",
    "Show Resources": "显示资源",
    "Hide resources": "隐藏资源",
    "v0.1.0c Tiny Fix": "v0.1.0c 微量 bug 修复",
    "v0.1.0b Small Fixes": "v0.1.0b 小型 bug 修复",
    "v0.1.0a Small Fixes": "v0.1.0a 小型 bug 修复",
    "v0.1.0 Big Update": "v0.1.0 大型更新",
    "v0.0.5c Small Hotfix Update": "v0.0.5c 小型热更新",
    "v0.0.5b Small Hotfix Update": "v0.0.5b 小型热更新",
    "v0.0.5a Small Hotfix Update": "v0.0.5a 小型热更新",
    "v0.0.5 Content Update": "v0.0.5 内容更新",
    "v0.0.4a Hotfix": "v0.0.4a 热更新",
    "v0.0.4 Minor update": "v0.0.4 次要更新",
    "v0.0.3b Mobile friendly UI version": "v0.0.3b 移动端友好界面更新",
    "v0.0.3a Hotfix update": "v0.0.3a 热更新",
    "v0.0.3 Minor update": "v0.0.3 次要更新",
    "v0.0.2d Small update": "v0.0.2d 小型更新",
    "v0.0.2c Small hotfix update": "v0.0.2c 小型热更新",
    "v0.0.2b Expeditions added": "v0.0.2b 增加探险",
    "v0.0.2a Small UI updates": "v0.0.2a 小型 UI 更新",
    "v0.0.2 Prestige mechanics & New content": "v0.0.2 重置机制和新内容",
    "v0.0.1a UI and small features update": "v0.0.1a UI 和小型功能更新",
    "v0.0.1 First Playable Prototype": "v0.0.1 首个可玩的原型版本",
    'Added "Weather" mechanics, available on some planets': "加入了“天气”机制，在某些行星上可用",
    'Increased "Expeditions" rewards': "提升了探险战利品的数量",
    'Added "Expeditions" - active way to speed up getting resources': "增加了“探险”机制——一种主动获取资源的手段",
    'Transmit knowledge only available once you have more than 50 colonizers and did "Great Radio Transmitter" under landing zone upgrades section': "传输知识只在你拥有超过50位殖民者，并完成了大型无线电发射机的升级之后，才可用",
    'The most common type of exoplanets discovered so far are known as "super-Earths - exoplanets that have a mass and size larger than Earth but smaller than that of gas giants like Neptune or Jupiter. They typically range in size from about 1 to 10 times the mass of Earth.': "迄今为止发现的最常见的系外行星类型被称为“超级地球”——质量和尺寸大于地球但小于海王星或木星等气态巨行星的系外行星。它们的尺寸通常约为地球的 1 至 10 倍 地球的质量。",
    'The first exoplanet discovered around a Sun-like star in the "habitable zone" with Earth-like conditions is called Kepler-452b.': "在类似太阳的恒星周围发现的第一颗系外行星位于“宜居带”，具有类似地球的条件，称为开普勒-452b。",

    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Resource: ": "资源：",
    "Goal: ": "目标：",
    "Allows drilling harder materials. Also improve stone output by ": "允许开采更硬的材料。 同时提高石头产量 ",
    "Improves Charge Output by ": "将电力输出提高 ",
    "Upgrade: ": "升级: ",
    "Building: ": "建筑: ",
    "Improves energy storage by ": "提升电力存储 ",
    "Happiness: ": "幸福: ",
    "Job: ": "工作: ",
    "Research: ": "研究: ",
    "Crafting: ": "制作: ",
    "You know how to review a candidate for a future colony, and how to act when things go wrong. Every point decreases healthcare requirements by ": "你知道如何审查未来殖民地的候选人，以及当出现问题时如何采取行动。 每增加一点，医疗保健要求就会减少 ",
    "Solid materials are important, but so are other states of matter. Every point boosts oxygen and water production ": "固体材料很重要，但其他物质状态也很重要。 每一点增加氧气和水的产生 ",
    "Striking the earth can be done in a wide variety of ways. Every point boosts stone, ore, iron and platinum production by ": "可以通过多种方式撞击地球。 每一点都会使石头、矿石、铁和铂的产量提高 ",
    "You are not easily bored and know how to distract people from boredom. Every point decreases entertainment requirements by ": "你不容易感到无聊，并且知道如何分散人们对无聊的注意力。 每一点减少娱乐需求 ",
    "Be more efficient in your precious biomass usage. Every point boosts biomass based creatable resources production (such as plastic and rubber) by ": "更有效地利用宝贵的生物质。 每一点都会使基于生物质的可创造资源（例如塑料和橡胶）产量提高 ",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\/([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^\/ ([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Transmit Knowledge Upgrades: (.+) points left$/, '传输知识升级：还剩 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) hr$/, '$1 小时'],
    [/^([\d\.,]+) min$/, '$1 分钟'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);